version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: spadin/frontendapp
    volumes:
      - .:/var/app/
      - node_modules:/var/app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      npm run webpack-dev-server --
        --hot
        --inline
        --host=0.0.0.0
        --https
        --port=443
        --content-base=dist
        --history-api-fallback
  server:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: spadin/nginx-alpine-ssl
    depends_on:
      - frontend
    ports:
      - 443:443
volumes:
  node_modules: {}
