FROM spadin/frontendapp

ENV APP_HOME /var/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY webpack.config.js $APP_HOME/webpack.config.js
COPY package.json $APP_HOME/package.json
RUN npm install

COPY ./src  $APP_HOME/src
COPY ./test $APP_HOME/test
