version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: spadin/frontendapp
    volumes:
      - .:/var/app/
      - node_modules:/var/app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      npm run webpack-dev-server --
        --hot
        --inline
        --host=0.0.0.0
        --https
        --cert=/var/app/nginx/server.crt
        --key=/var/app/nginx/server.key
        --port=443
        --content-base=dist
        --history-api-fallback
  server:
    image: nginx:1.11-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/etc/nginx/ssl/
    depends_on:
      - frontend
    ports:
      - 443:443
volumes:
  node_modules: {}
