version: '2'
services:
  frontend:
    build:
      context: ../../
      dockerfile: ./config/production/Dockerfile
    image: spadin/frontendapp
    volumes:
      - ../../:/var/app/
      - node_modules:/var/app/node_modules
    ports:
      - 8080:8080
volumes:
  node_modules: {}
